AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  TweetProcessor:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      CodeUri: target/retweet-leaderboard-1.0.4-SNAPSHOT.jar
      Handler: com.jlhood.retweetcounter.lambda.TweetProcessorHandler::handleRequest
      Tracing: Active
      MemorySize: 512
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Leaderboard
      Environment:
        Variables:
          LEADERBOARD_TABLE_NAME: !Ref Leaderboard

  GetLeaderboard:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java8
      CodeUri: target/retweet-leaderboard-1.0.4-SNAPSHOT.jar
      Handler: com.jlhood.retweetcounter.lambda.GetLeaderboardHandler::handleRequest
      Tracing: Active
      MemorySize: 512
      Timeout: 60
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Leaderboard
      Environment:
        Variables:
          LEADERBOARD_TABLE_NAME: !Ref Leaderboard
      Events:
        GetLeaderboardApi:
          Type: Api
          Properties:
            Path: /leaderboard
            Method: get

  Leaderboard:
    Type: AWS::Serverless::SimpleTable
    Properties:
      ProvisionedThroughput:
        ReadCapacityUnits: 10
        WriteCapacityUnits: 10
